/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static swingui.Connector.conn;

/**
 *
 * @author hp
 */
public class Transactions extends javax.swing.JFrame {

    /**
     * Creates new form Transactions
     */
    public Transactions() {
        initComponents();
        showDate();
    }
    public void showDate()
    {
        Date d=new Date();
        SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
        Date1Text.setText(sf.format(d));
        Date2Text.setText(sf.format(d));
        Date3Text.setText(sf.format(d));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DepositeButton = new javax.swing.JButton();
        AccNo1Text = new javax.swing.JTextField();
        Name1Text = new javax.swing.JTextField();
        Balance1Text = new javax.swing.JTextField();
        DepositAmountText = new javax.swing.JTextField();
        Search1Button = new javax.swing.JButton();
        NewBalance1Text = new javax.swing.JTextField();
        NewBalance1Button = new javax.swing.JButton();
        Clear1Button = new javax.swing.JButton();
        Date1Text = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        AccNo2Text = new javax.swing.JTextField();
        Name2Text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Balance2Text = new javax.swing.JTextField();
        WithDrawAmountText = new javax.swing.JTextField();
        WithdrawButton = new javax.swing.JButton();
        Search2Button = new javax.swing.JButton();
        NewBalance2Text = new javax.swing.JTextField();
        NewBalance2Button = new javax.swing.JButton();
        Clear2Button = new javax.swing.JButton();
        Date2Text = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        AccNo3Text = new javax.swing.JTextField();
        Name3Text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Balance3Text = new javax.swing.JTextField();
        PayeeAccNoText = new javax.swing.JTextField();
        TransferButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TransferAmountText = new javax.swing.JTextField();
        Search3Button = new javax.swing.JButton();
        NewBalance3Button = new javax.swing.JButton();
        NewBalance3Text = new javax.swing.JTextField();
        Clear3Button = new javax.swing.JButton();
        Date3Text = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        AccNo4Text = new javax.swing.JTextField();
        Name4Text = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Balance4Text = new javax.swing.JTextField();
        ViewBalanceButton = new javax.swing.JButton();
        Clear4Button = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swingui/bankmanagement.jpg"))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 0));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 4), "TRANSACTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(153, 0, 153))); // NOI18N
        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Account Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Available Balance");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Deposite Amount");

        DepositeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DepositeButton.setText("DEPOSITE");
        DepositeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositeButtonActionPerformed(evt);
            }
        });

        Name1Text.setEditable(false);

        Balance1Text.setEditable(false);

        Search1Button.setText("Search");
        Search1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ButtonActionPerformed(evt);
            }
        });

        NewBalance1Text.setEditable(false);

        NewBalance1Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewBalance1Button.setText("New Balance");
        NewBalance1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBalance1ButtonActionPerformed(evt);
            }
        });

        Clear1Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear1Button.setText("CLEAR");
        Clear1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear1ButtonActionPerformed(evt);
            }
        });

        Date1Text.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NewBalance1Button)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(NewBalance1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(DepositeButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                                        .addComponent(Clear1Button))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(DepositAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Name1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(Balance1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AccNo1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(71, 71, 71)
                        .addComponent(Search1Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Date1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(AccNo1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search1Button))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Name1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Balance1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Date1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DepositAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBalance1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewBalance1Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepositeButton)
                    .addComponent(Clear1Button))
                .addContainerGap())
        );

        jTabbedPane1.addTab("DEPOSITE", jPanel1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Account Number");

        Name2Text.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Available Balance");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Withdraw Amount");

        Balance2Text.setEditable(false);

        WithdrawButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WithdrawButton.setText("WITHDRAW");
        WithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawButtonActionPerformed(evt);
            }
        });

        Search2Button.setText("Search");
        Search2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search2ButtonActionPerformed(evt);
            }
        });

        NewBalance2Text.setEditable(false);

        NewBalance2Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewBalance2Button.setText("New Balance");
        NewBalance2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBalance2ButtonActionPerformed(evt);
            }
        });

        Clear2Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear2Button.setText("CLEAR");
        Clear2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear2ButtonActionPerformed(evt);
            }
        });

        Date2Text.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(NewBalance2Button)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(WithdrawButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                                .addComponent(Clear2Button))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(NewBalance2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(Balance2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AccNo2Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Name2Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(31, 31, 31)
                                .addComponent(Search2Button))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(WithDrawAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Date2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(AccNo2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search2Button))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Name2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Balance2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Date2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(WithDrawAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBalance2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewBalance2Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WithdrawButton)
                    .addComponent(Clear2Button))
                .addContainerGap())
        );

        jTabbedPane1.addTab("WITHDRAW", jPanel3);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Account Number");

        Name3Text.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Available Balance");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Payee Account No");

        Balance3Text.setEditable(false);

        TransferButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TransferButton.setText("TRANSFER");
        TransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Transfer Amount");

        Search3Button.setText("Search");
        Search3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search3ButtonActionPerformed(evt);
            }
        });

        NewBalance3Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewBalance3Button.setText("New Balance");
        NewBalance3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBalance3ButtonActionPerformed(evt);
            }
        });

        NewBalance3Text.setEditable(false);

        Clear3Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear3Button.setText("CLEAR");
        Clear3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear3ButtonActionPerformed(evt);
            }
        });

        Date3Text.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(NewBalance3Button)
                                        .addComponent(jLabel14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PayeeAccNoText, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(TransferAmountText)
                                    .addComponent(NewBalance3Text)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(Balance3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AccNo3Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Name3Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36)
                                .addComponent(Search3Button)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TransferButton)
                        .addGap(158, 158, 158)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clear3Button, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Date3Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(AccNo3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search3Button))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Name3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Balance3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Date3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(PayeeAccNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TransferAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBalance3Button)
                    .addComponent(NewBalance3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Clear3Button)
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TransferButton)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("TRANSFER", jPanel4);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Account Number");

        Name4Text.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Name");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Available Balance");

        Balance4Text.setEditable(false);

        ViewBalanceButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ViewBalanceButton.setText("VIEW BALANCE");
        ViewBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBalanceButtonActionPerformed(evt);
            }
        });

        Clear4Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear4Button.setText("CLEAR");
        Clear4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear4ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(ViewBalanceButton)
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Clear4Button)
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(Balance4Text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AccNo4Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Name4Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(169, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(ViewBalanceButton)
                .addGap(18, 18, 18)
                .addComponent(Clear4Button)
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(AccNo4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(Name4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(Balance4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(179, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("VIEW BALANCE", jPanel2);

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackButton)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("DEPOSITE");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepositeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositeButtonActionPerformed
        Connector con=new Connector();
        con.createConnection();
        try
        {
            Statement stmt=Connector.conn.createStatement();
            PreparedStatement pst,pst1,pst2;
            String sql="update customer set balance=? where AccNo=?";
            pst=Connector.conn.prepareStatement(sql);
            pst.setString(1,NewBalance1Text.getText());
            pst.setString(2,AccNo1Text.getText());
            pst.execute();
            String sql1="update balances set balance=? where AccNo=?;";
            pst1=Connector.conn.prepareStatement(sql1);
            pst1.setString(1,NewBalance1Text.getText());
            pst1.setString(2,AccNo1Text.getText());
            pst1.execute();
            String sql2="insert into viewtransactions(TransactionId,TransactionType,AccNo,Balance,Date,Amount) values(2,'Deposite',?,?,?,?);";
            pst2=Connector.conn.prepareStatement(sql2);
            pst2.setString(2,NewBalance1Text.getText());
            pst2.setString(1,AccNo1Text.getText());
            pst2.setString(3,Date1Text.getText());
            pst2.setString(4,DepositAmountText.getText());
            pst2.execute();
            
             JOptionPane.showMessageDialog(null,"Records Updated");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DepositeButtonActionPerformed

    private void WithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawButtonActionPerformed
        Connector con=new Connector();
        con.createConnection();
        try
        {
            Statement stmt=Connector.conn.createStatement();
            PreparedStatement pst,pst1,pst2;
            String sql="update customer set balance=? where AccNo=?";
            pst=Connector.conn.prepareStatement(sql);
            pst.setString(1,NewBalance2Text.getText());
            pst.setString(2,AccNo2Text.getText());
            pst.execute();
            String sql1="update balances set balance=? where AccNo=?;";
            pst1=Connector.conn.prepareStatement(sql1);
            pst1.setString(1,NewBalance2Text.getText());
            pst1.setString(2,AccNo2Text.getText());
            pst1.execute();
            String sql2="insert into viewtransactions(TransactionId,TransactionType,AccNo,Balance,Date,Amount) values(1,'Withdraw',?,?,?,?);";
            pst2=Connector.conn.prepareStatement(sql2);
            pst2.setString(2,NewBalance2Text.getText());
            pst2.setString(1,AccNo2Text.getText());
            pst2.setString(3,Date2Text.getText());
            pst2.setString(4,WithDrawAmountText.getText());
            pst2.execute();
            
             JOptionPane.showMessageDialog(null,"Records Updated");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_WithdrawButtonActionPerformed

    private void TransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferButtonActionPerformed
       Connector con=new Connector();
       con.createConnection();
       try{
           Statement smt=Connector.conn.createStatement();
           
           PreparedStatement p,p1,p2,p3;
            int payeebalance=0;
            int totalbalance=0;
            int bal=Integer.parseInt(TransferAmountText.getText());
            String sql1="select balance from customer where AccNo=?";
            p1=Connector.conn.prepareStatement(sql1);
            p1.setString(1,PayeeAccNoText.getText());
            ResultSet rs=p1.executeQuery();
            while(rs.next())
            {
                payeebalance=Integer.parseInt(rs.getString("balance"));
                totalbalance=payeebalance+bal;
            }
             String sql5="insert into viewtransactions(TransactionId,TransactionType,AccNo,Balance,Date,Amount) values(4,'Credit',?,?,?,?);";
            p2=Connector.conn.prepareStatement(sql5);
            p2.setString(2,String.valueOf(totalbalance));
            p2.setString(1,PayeeAccNoText.getText());
            p2.setString(3,Date3Text.getText());
            p2.setString(4,TransferAmountText.getText());
            p2.execute();
           
            String sql="update customer set balance=? where AccNo=?";
            p=Connector.conn.prepareStatement(sql);
            p.setString(1,String.valueOf(totalbalance));
            p.setString(2,PayeeAccNoText.getText());
            p.execute();
            
            String sql6="update balances set balance=? where AccNo=?";
            p3=Connector.conn.prepareStatement(sql6);
            p3.setString(1,String.valueOf(totalbalance));
            p3.setString(2,PayeeAccNoText.getText());
            
           PreparedStatement pst1,pst2,pst3;
           String sql2="update customer set balance=? where AccNo=?";
            pst1=Connector.conn.prepareStatement(sql2);
            pst1.setString(1,NewBalance3Text.getText());
            pst1.setString(2,AccNo3Text.getText());
            pst1.execute();
            
            String sql3="update balances set balance=? where AccNo=?;";
            pst1=Connector.conn.prepareStatement(sql3);
            pst1.setString(1,NewBalance3Text.getText());
            pst1.setString(2,AccNo3Text.getText());
            pst1.execute();
            
            String sql4="insert into viewtransactions(TransactionId,TransactionType,AccNo,Balance,Date,Amount) values(3,'Transfer',?,?,?,?);";
            pst2=Connector.conn.prepareStatement(sql4);
            pst2.setString(2,NewBalance3Text.getText());
            pst2.setString(1,AccNo3Text.getText());
            pst2.setString(3,Date3Text.getText());
            pst2.setString(4,TransferAmountText.getText());
            pst2.execute();
           
           JOptionPane.showMessageDialog(null,"Transfer Completed");
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_TransferButtonActionPerformed

    private void ViewBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBalanceButtonActionPerformed
         Connector con=new Connector();
        con.createConnection();
        try
        {
            Statement stmt=Connector.conn.createStatement();
            PreparedStatement pst;
            String sql="select CustomerName,Balance from customer where AccNo=?;";
            pst=Connector.conn.prepareStatement(sql);
            pst.setString(1,AccNo4Text.getText());
            ResultSet result = pst.executeQuery();
            
            while(result.next())
            {
            Name4Text.setText(result.getString("CustomerName"));
            Balance4Text.setText(result.getString("Balance"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ViewBalanceButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        Welcome w=new Welcome();
        w.Welcome();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void Search1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ButtonActionPerformed
        Connector con=new Connector();
        con.createConnection();
        try
        {
            Statement stmt=Connector.conn.createStatement();
            PreparedStatement pst;
            String sql="select CustomerName,Balance from customer where AccNo=?;";
            pst=Connector.conn.prepareStatement(sql);
            pst.setString(1,AccNo1Text.getText());
            ResultSet result = pst.executeQuery();
            
            while(result.next())
            {
            Name1Text.setText(result.getString("CustomerName"));
            Balance1Text.setText(result.getString("Balance"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Search1ButtonActionPerformed

    private void NewBalance1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBalance1ButtonActionPerformed
         Connector con=new Connector();
         con.createConnection();
         try{
         
        int a=Integer.parseInt(Balance1Text.getText());
        int b=Integer.parseInt(DepositAmountText.getText());
        
        int result=a+b;
        
        NewBalance1Text.setText(String.valueOf(result));
        
        Statement stmt=conn.createStatement();
            PreparedStatement pst;
            String sql="update customer set balance=? where AccNo=?; ";
            pst=conn.prepareStatement(sql);
            pst.setString(1,NewBalance1Text.getText());
            pst.setString(2,AccNo1Text.getText());
            pst.execute();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_NewBalance1ButtonActionPerformed

    private void Search2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search2ButtonActionPerformed
         Connector con=new Connector();
        con.createConnection();
        try
        {
            Statement stmt=Connector.conn.createStatement();
            PreparedStatement pst;
            String sql="select CustomerName,Balance from customer where AccNo=?;";
            pst=Connector.conn.prepareStatement(sql);
            pst.setString(1,AccNo2Text.getText());
            ResultSet result = pst.executeQuery();
            
            while(result.next())
            {
            Name2Text.setText(result.getString("CustomerName"));
            Balance2Text.setText(result.getString("Balance"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Search2ButtonActionPerformed

    private void Search3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search3ButtonActionPerformed
         Connector con=new Connector();
        con.createConnection();
        try
        {
            Statement stmt=Connector.conn.createStatement();
            PreparedStatement pst;
            String sql="select CustomerName,Balance from customer where AccNo=?;";
            pst=Connector.conn.prepareStatement(sql);
            pst.setString(1,AccNo3Text.getText());
            ResultSet result = pst.executeQuery();
            
            while(result.next())
            {
            Name3Text.setText(result.getString("CustomerName"));
            Balance3Text.setText(result.getString("Balance"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Search3ButtonActionPerformed

    private void NewBalance2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBalance2ButtonActionPerformed
        int a=Integer.parseInt(Balance2Text.getText());
        int b=Integer.parseInt(WithDrawAmountText.getText());
        
        int result=a-b;
        
        NewBalance2Text.setText(String.valueOf(result));
    }//GEN-LAST:event_NewBalance2ButtonActionPerformed

    private void NewBalance3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBalance3ButtonActionPerformed
       int a=Integer.parseInt(Balance3Text.getText());
        int b=Integer.parseInt(TransferAmountText.getText());
        
        int result=a-b;
        
        NewBalance3Text.setText(String.valueOf(result));
        Connector con=new Connector();
        con.createConnection();
        try
        {
            Statement smt=Connector.conn.createStatement();
            
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_NewBalance3ButtonActionPerformed

    private void Clear1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear1ButtonActionPerformed
       AccNo1Text.setText("");
       Name1Text.setText("");
       Balance1Text.setText("");
       DepositAmountText.setText("");
       NewBalance1Text.setText("");
       
    }//GEN-LAST:event_Clear1ButtonActionPerformed

    private void Clear2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear2ButtonActionPerformed
        AccNo2Text.setText("");
       Name2Text.setText("");
       Balance2Text.setText("");
       WithDrawAmountText.setText("");
       NewBalance2Text.setText("");
    }//GEN-LAST:event_Clear2ButtonActionPerformed

    private void Clear3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear3ButtonActionPerformed
        AccNo3Text.setText("");
       Name3Text.setText("");
       Balance3Text.setText("");
       PayeeAccNoText.setText("");
       TransferAmountText.setText("");
       NewBalance3Text.setText("");
    }//GEN-LAST:event_Clear3ButtonActionPerformed

    private void Clear4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear4ButtonActionPerformed
         AccNo4Text.setText("");
       Name4Text.setText("");
       Balance4Text.setText("");
    }//GEN-LAST:event_Clear4ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Transactions () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNo1Text;
    private javax.swing.JTextField AccNo2Text;
    private javax.swing.JTextField AccNo3Text;
    private javax.swing.JTextField AccNo4Text;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField Balance1Text;
    private javax.swing.JTextField Balance2Text;
    private javax.swing.JTextField Balance3Text;
    private javax.swing.JTextField Balance4Text;
    private javax.swing.JButton Clear1Button;
    private javax.swing.JButton Clear2Button;
    private javax.swing.JButton Clear3Button;
    private javax.swing.JButton Clear4Button;
    private javax.swing.JTextField Date1Text;
    private javax.swing.JTextField Date2Text;
    private javax.swing.JTextField Date3Text;
    private javax.swing.JTextField DepositAmountText;
    private javax.swing.JButton DepositeButton;
    private javax.swing.JTextField Name1Text;
    private javax.swing.JTextField Name2Text;
    private javax.swing.JTextField Name3Text;
    private javax.swing.JTextField Name4Text;
    private javax.swing.JButton NewBalance1Button;
    private javax.swing.JTextField NewBalance1Text;
    private javax.swing.JButton NewBalance2Button;
    private javax.swing.JTextField NewBalance2Text;
    private javax.swing.JButton NewBalance3Button;
    private javax.swing.JTextField NewBalance3Text;
    private javax.swing.JTextField PayeeAccNoText;
    private javax.swing.JButton Search1Button;
    private javax.swing.JButton Search2Button;
    private javax.swing.JButton Search3Button;
    private javax.swing.JTextField TransferAmountText;
    private javax.swing.JButton TransferButton;
    private javax.swing.JButton ViewBalanceButton;
    private javax.swing.JTextField WithDrawAmountText;
    private javax.swing.JButton WithdrawButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
