/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ViewTransactions extends javax.swing.JFrame {

    /**
     * Creates new form ViewTransactions
     */
    public ViewTransactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AllTransactionsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AccNoText = new javax.swing.JTextField();
        AccTRansactionBUtton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DateText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DateTransactionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TransactionTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("VIEW TRANSACTIONS");

        AllTransactionsButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AllTransactionsButton.setText("View All Transactions");
        AllTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllTransactionsButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter Account Number");

        AccTRansactionBUtton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AccTRansactionBUtton.setText("View Transactions");
        AccTRansactionBUtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccTRansactionBUttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enter Date");

        jLabel4.setText("Format:      yyyy/mm/dd");

        DateTransactionButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DateTransactionButton.setText("View Transactions");
        DateTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTransactionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AllTransactionsButton)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AccNoText)
                            .addComponent(DateText)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccTRansactionBUtton)
                            .addComponent(DateTransactionButton))
                        .addContainerGap(54, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AllTransactionsButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AccNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccTRansactionBUtton))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTransactionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TransactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Number", "Transaction Type", "Amount", "Date", "Total Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TransactionTable);
        if (TransactionTable.getColumnModel().getColumnCount() > 0) {
            TransactionTable.getColumnModel().getColumn(0).setResizable(false);
            TransactionTable.getColumnModel().getColumn(1).setResizable(false);
            TransactionTable.getColumnModel().getColumn(2).setResizable(false);
            TransactionTable.getColumnModel().getColumn(3).setResizable(false);
            TransactionTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        Welcome w=new Welcome();
        w.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AllTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllTransactionsButtonActionPerformed
        Connector con=new Connector();
               con.createConnection();
               
        try{
            DefaultTableModel model; 
            model =(DefaultTableModel) TransactionTable.getModel();
            model.setRowCount(0);
            Statement stmt=Connector.conn.createStatement();
            String sql="select AccNo,TransactionType,Amount,Date,Balance from viewtransactions ";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                String accno=rs.getString("AccNo");
                String ttype=rs.getString("TransactionType");
                String amount=rs.getString("Amount");
                String date=rs.getString("Date");
                String balance=rs.getString("Balance");
                model.addRow(new Object[] {accno,ttype,amount,date,balance});
            }
            rs.close();
            stmt.close();
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_AllTransactionsButtonActionPerformed

    private void AccTRansactionBUttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccTRansactionBUttonActionPerformed
        Connector con=new Connector();
               con.createConnection();
               
        try{
            DefaultTableModel model; 
            model =(DefaultTableModel) TransactionTable.getModel();
            model.setRowCount(0);
            Statement stmt=Connector.conn.createStatement();
            PreparedStatement p;
            String sql="select AccNo,TransactionType,Amount,Date,Balance from viewtransactions where AccNo=? ;";
            p=Connector.conn.prepareStatement(sql);
            p.setString(1,AccNoText.getText());
            ResultSet rs=p.executeQuery();
            while(rs.next())
            {
                String accno=rs.getString("AccNo");
                String ttype=rs.getString("TransactionType");
                String amount=rs.getString("Amount");
                String date=rs.getString("Date");
                String balance=rs.getString("Balance");
                model.addRow(new Object[] {accno,ttype,amount,date,balance});
            }
            rs.close();
            stmt.close();
            AccNoText.setText("");
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_AccTRansactionBUttonActionPerformed

    private void DateTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTransactionButtonActionPerformed
        Connector con=new Connector();
               con.createConnection();
               
        try{
            DefaultTableModel model; 
            model =(DefaultTableModel) TransactionTable.getModel();
            model.setRowCount(0);
            Statement stmt=Connector.conn.createStatement();
            PreparedStatement p;
            String sql="select AccNo,TransactionType,Amount,Date,Balance from viewtransactions where Date=? ;";
            p=Connector.conn.prepareStatement(sql);
            p.setString(1,DateText.getText());
            ResultSet rs=p.executeQuery();
            while(rs.next())
            {
                String accno=rs.getString("AccNo");
                String ttype=rs.getString("TransactionType");
                String amount=rs.getString("Amount");
                String date=rs.getString("Date");
                String balance=rs.getString("Balance");
                model.addRow(new Object[] {accno,ttype,amount,date,balance});
            }
            rs.close();
            stmt.close();
            DateText.setText("");
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_DateTransactionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void ViewTransactions() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNoText;
    private javax.swing.JButton AccTRansactionBUtton;
    private javax.swing.JButton AllTransactionsButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField DateText;
    private javax.swing.JButton DateTransactionButton;
    private javax.swing.JTable TransactionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
