/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingui;

/**
 *
 * @author hp
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NewAccCreationButton = new javax.swing.JButton();
        ViewCustomersButton = new javax.swing.JButton();
        TransactionsButton = new javax.swing.JButton();
        ViewTransactionsButton = new javax.swing.JButton();
        BranchTableButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        DeleteCustomersButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swingui/welcome.jpg"))); // NOI18N

        NewAccCreationButton.setBackground(new java.awt.Color(0, 0, 204));
        NewAccCreationButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewAccCreationButton.setForeground(new java.awt.Color(255, 255, 255));
        NewAccCreationButton.setText("New Account Creation");
        NewAccCreationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAccCreationButtonActionPerformed(evt);
            }
        });

        ViewCustomersButton.setBackground(new java.awt.Color(0, 0, 204));
        ViewCustomersButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewCustomersButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewCustomersButton.setText("View Customers");
        ViewCustomersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustomersButtonActionPerformed(evt);
            }
        });

        TransactionsButton.setBackground(new java.awt.Color(0, 0, 204));
        TransactionsButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TransactionsButton.setForeground(new java.awt.Color(255, 255, 255));
        TransactionsButton.setText("Transactions");
        TransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionsButtonActionPerformed(evt);
            }
        });

        ViewTransactionsButton.setBackground(new java.awt.Color(0, 0, 204));
        ViewTransactionsButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewTransactionsButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewTransactionsButton.setText("View Transactions");
        ViewTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTransactionsButtonActionPerformed(evt);
            }
        });

        BranchTableButton.setBackground(new java.awt.Color(0, 0, 204));
        BranchTableButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BranchTableButton.setForeground(new java.awt.Color(255, 255, 255));
        BranchTableButton.setText("Branch Table");
        BranchTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchTableButtonActionPerformed(evt);
            }
        });

        LogOutButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LogOutButton.setText("LOG OUT");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        DeleteCustomersButton.setBackground(new java.awt.Color(0, 0, 204));
        DeleteCustomersButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteCustomersButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteCustomersButton.setText("Delete Customers");
        DeleteCustomersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCustomersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewCustomersButton)
                    .addComponent(NewAccCreationButton)
                    .addComponent(BranchTableButton))
                .addGap(192, 192, 192)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TransactionsButton)
                    .addComponent(ViewTransactionsButton)
                    .addComponent(DeleteCustomersButton))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewAccCreationButton)
                    .addComponent(TransactionsButton))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewTransactionsButton)
                    .addComponent(ViewCustomersButton))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteCustomersButton)
                    .addComponent(BranchTableButton))
                .addGap(28, 28, 28)
                .addComponent(LogOutButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewAccCreationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAccCreationButtonActionPerformed
        this.dispose();
        Account a=new Account();
        a.setVisible(true);
    }//GEN-LAST:event_NewAccCreationButtonActionPerformed

    private void TransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionsButtonActionPerformed
        this.dispose();
        Transactions t=new Transactions();
        t.setVisible(true);
    }//GEN-LAST:event_TransactionsButtonActionPerformed

    private void ViewCustomersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustomersButtonActionPerformed
        this.dispose();
        ViewCustomers vc= new ViewCustomers();
        vc.setVisible(true);
    }//GEN-LAST:event_ViewCustomersButtonActionPerformed

    private void ViewTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTransactionsButtonActionPerformed
        this.dispose();
        ViewTransactions vt=new ViewTransactions();
        vt.setVisible(true);
    }//GEN-LAST:event_ViewTransactionsButtonActionPerformed

    private void BranchTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchTableButtonActionPerformed
        this.dispose();
        BranchDetails bd=new BranchDetails();
        bd.setVisible(true);
    }//GEN-LAST:event_BranchTableButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        this.dispose();
        LogIn l=new LogIn();
        l.setVisible(true);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void DeleteCustomersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCustomersButtonActionPerformed
        this.dispose();
        DeleteCustomers d=new DeleteCustomers();
        d.setVisible(true);
    }//GEN-LAST:event_DeleteCustomersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Welcome() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BranchTableButton;
    private javax.swing.JButton DeleteCustomersButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton NewAccCreationButton;
    private javax.swing.JButton TransactionsButton;
    private javax.swing.JButton ViewCustomersButton;
    private javax.swing.JButton ViewTransactionsButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
